import 'package:flutter/material.dart';
List <Color> colorsList=[
  Colors.purpleAccent,
  Colors.black,
  Colors.blue,
  Colors.yellow,
  Colors.orange,
  Colors.red,
  Colors.teal,
  const Color(0XFF824e4a),
  const Color(0XFFeb10d8),
  Colors.black12,
  Colors.cyan,
  Colors.brown,
  Colors.white,
  Colors.lightGreen,
  Colors.pink,
  Colors.teal,
  const Color(0XFF824e4a),
  const Color(0XFFeb10d8),
  Colors.purpleAccent,
  Colors.black,
  Colors.blue,
  Colors.yellow,
  Colors.orange,
  Colors.red,
  Colors.teal,
  const Color(0XFF824e4a),
  const Color(0XFFeb10d8),
  Colors.purpleAccent,
  Colors.black,
  Colors.blue,
  Colors.yellow,
  Colors.orange,
  Colors.red,
  Colors.teal,
  const Color(0XFF824e4a),
  const Color(0XFFeb10d8),
  Colors.purpleAccent,
  Colors.black,
  Colors.blue,
  Colors.yellow,
  Colors.orange,
  Colors.red,
  Colors.teal,
  const Color(0XFF824e4a),
  const Color(0XFFeb10d8),

];